TeamShelterProject/Models/Animal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamShelterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.ApplicationForAnimals = new HashSet<ApplicationForAnimal>();
            this.AnimalPictures = new HashSet<AnimalPicture>();
        }
    
        public int id { get; set; }
        public int workerId { get; set; }
        public string animalType { get; set; }
        public string name { get; set; }
        public string breed { get; set; }
        public string gender { get; set; }
        public System.DateTime birthDate { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> animalWeight { get; set; }
        public Nullable<System.DateTime> vacinationDate { get; set; }
        public Nullable<System.DateTime> dewormingDate { get; set; }
        public bool hasMicrochip { get; set; }
        public bool readyForAdoption { get; set; }
        public string comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationForAnimal> ApplicationForAnimals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalPicture> AnimalPictures { get; set; }
        public virtual Person Person { get; set; }
    }
}

TeamShelterProject/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeamShelterProject.Models;

namespace TeamShelterProject.Controllers
{
    public class AnimalsController : Controller
    {
        private ShelterProjectEntities db = new ShelterProjectEntities();

        // GET: Animals
        public ActionResult Index()
        {
            var animals = db.Animals.Include(a => a.Person).Include(a=> a.AnimalPictures);
            return View(animals.ToList());
        }

        // GET: Animals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animals.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        // GET: Animals/Create
        public ActionResult Create()
        {
            ViewBag.workerId = new SelectList(db.People, "id", "firstName");
            return View();
        }

        // POST: Animals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,workerId,animalType,name,breed,gender,birthDate,height,animalWeight,vacinationDate,dewormingDate,hasMicrochip,readyForAdoption,comments")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                db.Animals.Add(animal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.workerId = new SelectList(db.People, "id", "firstName", animal.workerId);
            return View(animal);
        }

        // GET: Animals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animals.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            ViewBag.workerId = new SelectList(db.People, "id", "firstName", animal.workerId);
            return View(animal);
        }

        // POST: Animals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,workerId,animalType,name,breed,gender,birthDate,height,animalWeight,vacinationDate,dewormingDate,hasMicrochip,readyForAdoption,comments")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(animal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.workerId = new SelectList(db.People, "id", "firstName", animal.workerId);
            return View(animal);
        }

        // GET: Animals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animals.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Animal animal = db.Animals.Find(id);
            db.Animals.Remove(animal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeamShelterProject/Controllers/ApplicationForAnimalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeamShelterProject.Models;

namespace TeamShelterProject.Controllers
{
    public class ApplicationForAnimalsController : Controller
    {
        private ShelterProjectEntities db = new ShelterProjectEntities();

        // GET: ApplicationForAnimals
        public ActionResult Index()
        {
            var applicationForAnimals = db.ApplicationForAnimals.Include(a => a.Animal).Include(a => a.Person);
            return View(applicationForAnimals.ToList());
        }

        // GET: ApplicationForAnimals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationForAnimal applicationForAnimal = db.ApplicationForAnimals.Find(id);
            if (applicationForAnimal == null)
            {
                return HttpNotFound();
            }
            return View(applicationForAnimal);
        }

        // GET: ApplicationForAnimals/Create
        public ActionResult Create()
        {
            ViewBag.animalId = new SelectList(db.Animals, "id", "animalType");
            ViewBag.workerId = new SelectList(db.People, "id", "firstName");
            return View();
        }

        // POST: ApplicationForAnimals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,animalId,workerId,firstName,surname,streetAddress,city,zipcode,phone,email,allergies,familySituation,numberOfKids,youngestKidAge,housingType,otherAnimals,animalComment,experience,reasonsToAdopt,timeAlone,tripOptions,possibilityForVet,infoSource,freeComment,owner")] ApplicationForAnimal applicationForAnimal)
        {
            if (ModelState.IsValid)
            {
                db.ApplicationForAnimals.Add(applicationForAnimal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.animalId = new SelectList(db.Animals, "id", "animalType", applicationForAnimal.animalId);
            ViewBag.workerId = new SelectList(db.People, "id", "firstName", applicationForAnimal.workerId);
            return View(applicationForAnimal);
        }

        // GET: ApplicationForAnimals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationForAnimal applicationForAnimal = db.ApplicationForAnimals.Find(id);
            if (applicationForAnimal == null)
            {
                return HttpNotFound();
            }
            ViewBag.animalId = new SelectList(db.Animals, "id", "animalType", applicationForAnimal.animalId);
            ViewBag.workerId = new SelectList(db.People, "id", "firstName", applicationForAnimal.workerId);
            return View(applicationForAnimal);
        }

        // POST: ApplicationForAnimals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,animalId,workerId,firstName,surname,streetAddress,city,zipcode,phone,email,allergies,familySituation,numberOfKids,youngestKidAge,housingType,otherAnimals,animalComment,experience,reasonsToAdopt,timeAlone,tripOptions,possibilityForVet,infoSource,freeComment,owner")] ApplicationForAnimal applicationForAnimal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationForAnimal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.animalId = new SelectList(db.Animals, "id", "animalType", applicationForAnimal.animalId);
            ViewBag.workerId = new SelectList(db.People, "id", "firstName", applicationForAnimal.workerId);
            return View(applicationForAnimal);
        }

        // GET: ApplicationForAnimals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationForAnimal applicationForAnimal = db.ApplicationForAnimals.Find(id);
            if (applicationForAnimal == null)
            {
                return HttpNotFound();
            }
            return View(applicationForAnimal);
        }

        // POST: ApplicationForAnimals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ApplicationForAnimal applicationForAnimal = db.ApplicationForAnimals.Find(id);
            db.ApplicationForAnimals.Remove(applicationForAnimal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeamShelterProject/Controllers/SheltersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeamShelterProject.Models;

namespace TeamShelterProject.Controllers
{
    public class SheltersController : Controller
    {
        private ShelterProjectEntities db = new ShelterProjectEntities();

   

        // GET: Shelters
        public ActionResult Index()
        {
            var people = db.Shelters.Include(a => a.People);
            return View(db.Shelters.ToList());
        }

        // GET: Shelters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            /*
            DbSet<Shelter> shelterinDbSet = db.Shelters;
            List<Shelter> shelterInListOfShelters = shelterinDbSet.ToList();
            Shelter shelter1 = db.Shelters.ToList()[0]; //get the only shelter we should get, if empty would crush
            */
           // Shelter shelter = db.Shelters.Include(s => s.People).Where(s=> s.id == id).FirstOrDefault(); //produces db set of 1 or 0 shelters, firstOrdefault takes the 1st item or null. Same as Find. We can't use find with Include. 
            // or better
            Shelter shelter = db.Shelters.Include(s => s.People).SingleOrDefault(s=> s.id == id);
            if (shelter == null)
            {
                return HttpNotFound();
            }
            return View(shelter);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Details(bool workerCheckBox, bool volunteerCheckBox)
        //{
            

        //    return View(shelter);
        //}

        // GET: Shelters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shelters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,streetAddress,phone,email")] Shelter shelter)
        {
            if (ModelState.IsValid)
            {
                db.Shelters.Add(shelter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(shelter);
        }

        // GET: Shelters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shelter shelter = db.Shelters.Find(id);
            if (shelter == null)
            {
                return HttpNotFound();
            }
            return View(shelter);
        }

        // POST: Shelters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,streetAddress,phone,email")] Shelter shelter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shelter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(shelter);
        }

        // GET: Shelters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shelter shelter = db.Shelters.Find(id);
            if (shelter == null)
            {
                return HttpNotFound();
            }
            return View(shelter);
        }

        // POST: Shelters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Shelter shelter = db.Shelters.Find(id);
            db.Shelters.Remove(shelter);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Partial()
        {
            db.Shelters.ToList();
            return PartialView();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeamShelterProject/Views/Shared/_Animal.cshtml
@model IEnumerable<TeamShelterProject.Models.Animal>

<ul class="all-animals js-all-animals">
    @foreach (var item in Model)
    {
        string imgpath = item.id + ".jpg";
        <li>
            
            <table class="table">
                <tr class="all-animals-row">
                    <td>
                        <h2>@Html.ActionLink(item.name, "../Animals/Details", new { id = item.id })</h2>
                    </td>
                    <td></td>

                </tr>
                <tr class="all-animals-row">
                    <td>
                        <img src="~/Content/animalImages/@imgpath" width="150" height="150" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.gender)
                        <br />
                        Breed: @Html.DisplayFor(modelItem => item.breed)
                        <br />
                        Date of birth: @Html.DisplayFor(modelItem => item.birthDate)
                    </td>
                </tr>
            </table>
        </li>
    }
</ul>

TeamShelterProject/Views/Shared/_ContactInformation.cshtml
@model IEnumerable<TeamShelterProject.Models.Person>

<table class="table">
    <tr>
        <th>
            Shelter Name
        </th>
        <th>
            Address
        </th>
        <th>
            Email
        </th>
        <th>
            Phone
        </th>
        <th>
            Administrator
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    if (item.personRole == 0)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Shelter.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shelter.streetAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shelter.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shelter.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
                @Html.DisplayFor(modelItem => item.surname)
            </td>
        </tr>
    }
}

</table>

TeamShelterProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Animal", "Index", "Animals")</li>
                    @if(User.Identity.IsAuthenticated==true){ <li>@Html.ActionLink("People", "Index", "People")</li>}
                    <li>@Html.ActionLink("Shelter Details", "Index", "Shelters")</li>
                    <li>@Html.ActionLink("Application", "Create", "ApplicationForAnimals")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/mySuperPupperScript")
    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TeamShelterProject/Views/Shared/_ListOfShelters.cshtml
@model IEnumerable<TeamShelterProject.Models.Shelter>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.streetAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.streetAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

TeamShelterProject/Views/Shared/_Shelter.cshtml
@model IEnumerable<TeamShelterProject.Models.Shelter>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.streetAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.streetAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        
    </tr>
}

</table>

TeamShelterProject/Views/Shared/_ShelterContactInformation.cshtml
@model IEnumerable<TeamShelterProject.Models.Shelter>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.streetAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th></th>
    </tr>
@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.streetAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>
    </tr>


}

</table>

TeamShelterProject/Views/Shared/_Workers.cshtml
@model IEnumerable<TeamShelterProject.Models.Person>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<h2>Workers</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surname)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.streetAddress)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.personRole)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Shelter.name)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    if (item.personRole == 1 || item.personRole == 0)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.firstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.surname)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.streetAddress)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.personRole)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Shelter.name)
        </td>*@
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>*@
    </tr>
    }
}

</table>

<h2>Volunteers</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surname)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.streetAddress)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.personRole)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Shelter.name)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.personRole == 2)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.firstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.surname)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.streetAddress)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.personRole)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shelter.name)
                </td>*@
                @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>*@
            </tr>
        }
    }

</table>